Quiz List SwiftUI
barbarakos/QuizApp pull request #32
Opened 2022-12-09 12:07 UTC by barbarakos

Created screen with list of quizzes divided in categories.
![Simulator Screen Shot - iPhone 14 Plus - 2022-12-09 at 12 57 13](https://user-images.githubusercontent.com/101199634/206699098-4a9d4519-ea36-4caf-935a-9d860424bb06.png)

2022-12-22 13:22 UTC, marinzg requested changes

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Extensions/LinearGradient.swift
> +    }
I see you've done that here, but please just do sth with line wrapping and formatting.

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/DifficultyViews.swift
> +        }
Maybe to avoid this switch/case, you could do sth like
```swift
// first
.foregroundColor(.yellow)
// second
.foregroundColor(type != .easy ? .yellow : emptyFillColor)
// third
.foregroundColor(type == .hard ? .yellow : emptyFillColor)
```

Because you'll always have to check, either with switch/case, if/else, ternary, but this way you're explicitly saying which view has which color in which case.
The naming `viewX: Color` is a bit confusing as well.

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/Models/CategorySection.swift
> +    var colorSwiftUI: Color {
Why SwiftUI suffix?

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizCellView.swift
> +    private var quiz: QuizModel!
Why implicit unwrap?

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizListView.swift
> +    func setSegmentedControlAppearance() {
Can this be `private`?

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizListView.swift
> +        let allCategories = CategorySection.allCases.map { $0.rawValue }
`segmentationalSelection` can also be an `@Published` var in view model to which you can subscribe there (combine sink) and do whatever you need and then update some other published var which will update the view.

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizListView.swift
> +                    let items = ["All"] + CategorySection.allCases.map {$0.rawValue}
This should be in VM.

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizListView.swift
> +                }
You can get rid of this if you move `segmentedSelection` into view model.

2022-12-22 13:22 UTC, marinzg commented on QuizApp/Quiz/QuizListView.swift
> +                }
Try to move as much as possible to view model and I think you'll be able to have only one `Section` view which will be updated and filtered through ViewModel.

2023-01-02 10:58 UTC, dorastipkovic requested changes

2023-01-02 10:58 UTC, dorastipkovic commented on QuizApp/Extensions/Color+Extensions.swift
> +        return Color(red: 0.988, green: 0.395, blue: 0.395)
You can omit `return`

2023-01-02 12:56 UTC, dorastipkovic approved these changes

2023-01-04 07:46 UTC, merged