Quiz Detail View SwiftUI
barbarakos/QuizApp pull request #33
Opened 2022-12-15 09:01 UTC by barbarakos

Added QuizInfoView and QuizDetailView in SwiftUI.
![Simulator Screen Shot - iPhone 14 Plus - 2022-12-15 at 09 59 33](https://user-images.githubusercontent.com/101199634/207817215-ca178db6-a6bc-4ad0-9549-fd987616e8bb.png)

2022-12-22 13:24 UTC, marinzg requested changes

2022-12-22 13:24 UTC, marinzg commented on QuizApp/Quiz/QuizDetailViews/QuizDetailView.swift
> +                                                                           numberOfQuestions: 5)))
Please fix indentation and newline breaks.

2022-12-22 13:24 UTC, marinzg commented on QuizApp/Quiz/QuizDetailViews/QuizInfoView.swift
> +                    print("Tapped start button!")
Remove debug print.

2023-01-02 11:07 UTC, dorastipkovic approved these changes

2023-01-04 07:47 UTC, merged