SearchView
barbarakos/QuizApp pull request #38
Opened 2022-12-21 09:57 UTC by barbarakos

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-21 at 10 54 49](https://user-images.githubusercontent.com/101199634/208876864-5a7e776c-a544-455f-823e-72b904be0821.png)
Added SearchView in SwiftUI.

2022-12-22 13:45 UTC, marinzg requested changes

2022-12-22 13:45 UTC, marinzg commented on QuizApp/Search/SearchView.swift
> +                    }
Everything that's not related to the drawing of the view should be in the view model.

2022-12-22 13:45 UTC, marinzg commented on QuizApp/Search/SearchView.swift
> +    }
Can this be in the viewModel as well?

2023-01-10 07:53 UTC, dorastipkovic approved these changes

2023-01-10 08:40 UTC, merged