UserViewController
barbarakos/QuizApp pull request #5
Opened 2022-10-11 07:11 UTC by barbarakos

- validating access tokens with check-api
- routing in SceneDelegate

2022-10-11 14:50 UTC, marinzg requested changes
Have you ran this code?
* response model doesn't have `accessToken` property
* LoginViewModel doesn't have required init
* `showLogIn` is not working

2022-10-11 14:50 UTC, marinzg commented on QuizApp/AppRouter/AppRouter.swift
> +//        navigationController.pushViewController(vc, animated: false)
Why did you leave this commented code?

2022-10-11 14:50 UTC, marinzg commented on QuizApp/CheckClient.swift
> +class CheckClient {
This logic can go into `LoginClient`.

2022-10-11 14:50 UTC, marinzg commented on QuizApp/CheckClient.swift
> +    let storage = SecureStorage()
`SecureStorage` is not a part of the architecture, but it contains some data so it would be best used in use case or data layer. It should not be used in client.

2022-10-11 14:50 UTC, marinzg commented on QuizApp/CheckClient.swift
> +    }
Next PR can be refactor to generic class ApiClient.

2022-10-11 14:50 UTC, marinzg commented on QuizApp/SceneDelegate.swift
> +                let checkClient = CheckClient()
Client can be referenced only in Data layer.

2022-10-11 14:50 UTC, marinzg commented on QuizApp/User/UserViewController.swift
> +    private var router: AppRouterProtocol!
Why does VC has reference to router?

2022-10-11 14:50 UTC, marinzg commented on QuizApp/User/UserViewController.swift
> +    convenience init(router: AppRouterProtocol) {
Why `convenience`?

2022-10-11 14:50 UTC, marinzg commented on QuizApp/SceneDelegate.swift
> +        window?.rootViewController = navigationController
Since this is an async call before, you'll have a black screen. Do you know how to improve this UX?

2022-10-11 14:50 UTC, marinzg commented on QuizApp/SceneDelegate.swift
> +                    router.showLogIn()
You can either make each function `@MainActor` or set whole AppRouter to be `@MainActor` to avoid using `DispatchQueue.main`

2022-10-13 08:49 UTC, barbarakos commented on QuizApp/CheckClient.swift
> +class CheckClient {
https://github.com/barbarakos/QuizApp/pull/8

2022-10-13 08:50 UTC, barbarakos commented on QuizApp/CheckClient.swift
> +    let storage = SecureStorage()
https://github.com/barbarakos/QuizApp/pull/8

2022-10-13 08:50 UTC, barbarakos commented on QuizApp/CheckClient.swift
> +    }
https://github.com/barbarakos/QuizApp/pull/8

2022-10-13 08:50 UTC, barbarakos commented on QuizApp/SceneDelegate.swift
> +                let checkClient = CheckClient()
https://github.com/barbarakos/QuizApp/pull/8

2022-10-13 08:50 UTC, barbarakos commented on QuizApp/SceneDelegate.swift
> +                    router.showLogIn()
https://github.com/barbarakos/QuizApp/pull/8

2022-10-14 10:53 UTC, marinzg approved these changes

2022-10-14 11:23 UTC, merged